apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config.yaml
  - database.yaml
  - minio.yaml
  - observability.yaml
  - tetra.yaml
  - worker.yaml
  - mockproc.yaml
