apiVersion: v1
kind: Service
metadata:
  name: mockproc
  namespace: tetra-system
spec:
  selector:
    app: mockproc
  ports:
    - port: 7000
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockproc
  namespace: tetra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockproc
  template:
    metadata:
      labels:
        app: mockproc
    spec:
      containers:
        - name: mockproc
          image: tetra-mockproc-image
          ports:
            - containerPort: 7000
          env:
            - name: MOCKPROC_HOST
              value: "0.0.0.0:7000"
            - name: MOCKPROC_FAILURE_RATE
              value: "0.1"
            - name: TETRA_OTEL_HOST
              value: "otel-collector:4317"
          readinessProbe:
            httpGet:
              path: /v1/liveness
              port: 7000
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
